"""Standalone evaluator for aphasia-friendly article summaries.

Given a generated bullet summary (a plain text file) and the source article
(a PDF), this rates how well the summary captures the article on four criteria
-- accuracy, coverage, simplicity, and clarity -- and prints a rating report.

This is intentionally self-contained: the only project dependency is the
OpenAI API key (read from readable_af's Config, or falling back to the
OPENAI_API_KEY environment variable / .env file). It evaluates *bullets only*;
it does not look at or score icons.

Usage:
    uv run python evaluate_summary.py SUMMARY.txt ARTICLE.pdf
    uv run python evaluate_summary.py SUMMARY.txt ARTICLE.pdf --json
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

from openai import OpenAI
from pydantic import BaseModel, Field
from pypdf import PdfReader

MODEL = "gpt-5-mini-2025-08-07"

# Truncate very long articles so we stay well within the context window. The
# full body is far more than is needed to judge accuracy/coverage of a handful
# of bullets, but we keep generously more than the abstract-only path does.
MAX_ARTICLE_CHARS = 60_000


# --------------------------------------------------------------------------- #
# Output schema
# --------------------------------------------------------------------------- #
class SummaryRating(BaseModel):
    accuracy: int = Field(
        ge=1,
        le=10,
        description="Does the summary introduce hallucinations or contradict the "
        "original? Is there anything that appears to misrepresent or oversimplify?",
    )
    coverage: int = Field(
        ge=1,
        le=10,
        description="Are the main arguments included? Are there critical details "
        "missing?",
    )
    simplicity: int = Field(
        ge=1,
        le=10,
        description="Is the word choice used simple enough for the reader?",
    )
    clarity: int = Field(
        ge=1,
        le=10,
        description="Would the meaning of each sentence be clear to people of all "
        "reading levels? Any sentences that MIGHT not make sense to a reader who is "
        "not informed on the topic should greatly reduce this score.",
    )


# --------------------------------------------------------------------------- #
# Input loading
# --------------------------------------------------------------------------- #
def extract_pdf_text(pdf_file: Path, max_chars: int = MAX_ARTICLE_CHARS) -> str:
    """Extract the text of every page of the article PDF."""
    reader = PdfReader(pdf_file)
    pages = [page.extract_text() or "" for page in reader.pages]
    text = "\n".join(pages).strip()
    if not text:
        raise ValueError(
            f"No extractable text found in {pdf_file}. Is it a scanned/image PDF?"
        )
    if len(text) > max_chars:
        text = text[:max_chars] + "\n\n[... article truncated for length ...]"
    return text


def load_bullets(summary_file: Path) -> list[str]:
    """Read a summary text file and return its bullets, one per line.

    Tolerates leading bullet markers (-, *, •). HTML tags (e.g. <b></b>) are left
    intact -- the rater is instructed to ignore them. Each non-empty line is
    treated as a bullet.
    """
    raw = summary_file.read_text(encoding="utf-8")
    bullets: list[str] = []
    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        line = re.sub(r"^[-*•]\s*", "", line).strip()  # drop leading bullet marker
        if line:
            bullets.append(line)
    if not bullets:
        raise ValueError(f"No summary bullets found in {summary_file}")
    return bullets


# --------------------------------------------------------------------------- #
# Evaluation
# --------------------------------------------------------------------------- #
def _api_key() -> str:
    """Resolve the OpenAI API key from the project Config, env, or .env file."""
    try:
        from readable_af.config import Config

        return Config.get().openai_api_key
    except Exception:
        pass
    key = os.getenv("OPENAI_API_KEY")
    if key:
        return key
    env = Path(".env")
    if env.exists():
        for line in env.read_text().splitlines():
            if line.startswith("OPENAI_API_KEY"):
                return line.split("=", 1)[1].strip().strip('"')
    raise RuntimeError(
        "Could not find OPENAI_API_KEY (checked Config, environment, and .env)."
    )


def evaluate(article_text: str, bullets: list[str]) -> SummaryRating:
    client = OpenAI(api_key=_api_key())
    bullets_text = "\n".join(f"- {b}" for b in bullets)

    system = (
        "You are an expert editor that processes summaries of scientific articles "
        "generated by another LLM. You will be passed the scientific article and the "
        "corresponding generated summary. Provide four numerical scores 1-10, one for "
        "each criterion. The evaluations should be strict. If a summary is rated too "
        "highly, this could negatively impact the user, but if rated too low, it will "
        "not be as detrimental. The summary may include HTML tags: these should not be "
        "considered. Evaluate the summary based on:\n\n"
        "Accuracy: Does the summary introduce hallucinations or contradict the "
        "original? Is there anything that appears to misrepresent or oversimplify?\n"
        "Coverage: Are the main arguments included? Are there critical details are "
        "missing?\n"
        "Simplicity: Is the word choice used simple enough for the reader?\n"
        "Clarity: Would the meaning of each sentence be clear to people of all reading "
        "levels? Any sentences that MIGHT not make sense to reader who is not informed "
        "on the topic should greatly reduce this score."
    )
    user = f"ARTICLE:\n{article_text}\n\nSUMMARY BULLETS:\n{bullets_text}"

    response = client.responses.parse(
        model=MODEL,
        input=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        text_format=SummaryRating,
    )
    if response.output_parsed is None:
        raise RuntimeError(f"Model did not return a parseable rating: {response.error}")
    return response.output_parsed


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #
def format_report(rating: SummaryRating, n_bullets: int) -> str:
    lines = [
        "=" * 60,
        "  AphasiaFriendly Summary Evaluation",
        "=" * 60,
        f"Bullets evaluated: {n_bullets}",
        "",
    ]
    for name in ("accuracy", "coverage", "simplicity", "clarity"):
        score: int = getattr(rating, name)
        lines.append(f"{name.capitalize():<12} {score:>2}/10")
    lines.append("=" * 60)
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Rate an aphasia-friendly bullet summary against its source article."
    )
    parser.add_argument("summary", type=Path, help="Path to the summary .txt file")
    parser.add_argument("article", type=Path, help="Path to the article .pdf file")
    parser.add_argument(
        "--json", action="store_true", help="Print the rating as JSON instead of a report"
    )
    args = parser.parse_args(argv)

    if not args.summary.exists():
        parser.error(f"Summary file not found: {args.summary}")
    if not args.article.exists():
        parser.error(f"Article PDF not found: {args.article}")

    bullets = load_bullets(args.summary)
    article_text = extract_pdf_text(args.article)
    rating = evaluate(article_text, bullets)

    if args.json:
        print(rating.model_dump_json(indent=2))
    else:
        print(format_report(rating, len(bullets)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
