name: Lint
on:
  push

jobs:
  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "format --check --diff"

